language: node_js

node_js:
  - 'stable'
  - 'lts/*'

script:
  - echo "Deploy"

install:
  - npm install -g firebase-tools

after_success:
  - npm install
  - cd functions; npm install; cd ..
  - firebase deploy --token $FIREBASE_TOKEN

