language: node_js

node_js:
  - "6.0"

script:
  - echo "Deploy"

install:
  - npm install -g firebase-tools

after_success:
  - npm install
  - cd functions; npm install; cd ..
  - firebase deploy --token $FIREBASE_TOKEN

